### PR TITLE
More generic env-excavation

### PR DESCRIPTION
**Pull request by wlonk**
Now with parameterized types!

See the changes in `README.rst` to see the new API that this provides. You can still use all the old functions, so it's not a breaking change, but I think it'll make things more friendly.

It also includes incidental documentation fixups, including fixing a lie about `env_int` which claimed it took a `separator` argument.

Also, I made the ordering of the kwargs consistent, which _shouldn't_ break anything—I hope people were using them kwargily, and not positionally. But it needed to happen.

_Have a cute animal, IF YOU DARE._

badgers

### CODE REVIEW

**Comment by wlonk** [comment]
@pipermerriam is still owner of this project on PyPI, so moving this PR to his fork.

**Comment by wlonk** [comment]
And now @pipermerriam has access to this repo again, so re-opening!

**Comment by jofusa** [comment]
+1. also +1 from the strong py.test fu

**Comment by pipermerriam** [comment]
:shipit:

**Pull request merged**
